import type { LevelData } from '../types';
import { shotgun, rifle, createBoxRoom } from './levels_common';

export const LEVELS_3: LevelData[] = [
  // ZONE 3: SUBWAY METRO (Trains & Slash) - Levels 81-90
  {
    id: 81,
    theme: 'metro',
    gridSize: { width: 20, height: 12 },
    playerSpawn: { x: 2, z: 2 },
    walls: [...createBoxRoom(20, 12)],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_81', pos: { x: 18, z: 2 }, hp: 100, weapon: { ...rifle } },
      { id: 'me2_81', pos: { x: 18, z: 10 }, hp: 100, weapon: { ...rifle } },
    ],
    ammoBoxes: [{ id: 'ma81', pos: { x: 10, z: 6 } }],
    exit: { x: 18, z: 6 },
  },
  {
    id: 82,
    theme: 'metro',
    gridSize: { width: 22, height: 14 },
    playerSpawn: { x: 2, z: 12 },
    walls: [...createBoxRoom(22, 14), { x: 11, z: 3 }, { x: 11, z: 11 }],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_82', pos: { x: 20, z: 2 }, hp: 120, weapon: { ...rifle } },
      { id: 'me2_82', pos: { x: 20, z: 12 }, hp: 120, weapon: { ...rifle } },
    ],
    ammoBoxes: [{ id: 'ma82', pos: { x: 11, z: 7 } }],
    exit: { x: 20, z: 7 },
  },
  {
    id: 83,
    theme: 'metro',
    gridSize: { width: 24, height: 12 },
    playerSpawn: { x: 2, z: 2 },
    walls: [...createBoxRoom(24, 12), { x: 12, z: 4 }, { x: 12, z: 8 }],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_83', pos: { x: 22, z: 2 }, hp: 150, weapon: { ...rifle } },
      { id: 'me2_83', pos: { x: 22, z: 10 }, hp: 150, weapon: { ...rifle } },
    ],
    ammoBoxes: [{ id: 'ma3', pos: { x: 12, z: 2 } }],
    exit: { x: 22, z: 6 },
  },
  {
    id: 84,
    theme: 'metro',
    gridSize: { width: 20, height: 16 },
    playerSpawn: { x: 10, z: 14 },
    walls: [...createBoxRoom(20, 16), { x: 5, z: 4 }, { x: 15, z: 4 }],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_84', pos: { x: 2, z: 2 }, hp: 150, weapon: { ...shotgun } },
      { id: 'me2_84', pos: { x: 18, z: 2 }, hp: 150, weapon: { ...shotgun } },
    ],
    healthBoxes: [{ id: 'mh4', pos: { x: 10, z: 2 } }],
    exit: { x: 10, z: 1 },
  },
  {
    id: 85,
    theme: 'metro',
    gridSize: { width: 26, height: 14 },
    playerSpawn: { x: 2, z: 7 },
    walls: [...createBoxRoom(26, 14), { x: 13, z: 3 }, { x: 13, z: 11 }],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_85', pos: { x: 24, z: 3 }, hp: 200, weapon: { ...rifle } },
      { id: 'me2_85', pos: { x: 24, z: 11 }, hp: 200, weapon: { ...rifle } },
    ],
    ammoBoxes: [{ id: 'ma85', pos: { x: 13, z: 7 } }],
    exit: { x: 24, z: 7 },
  },
  {
    id: 86,
    theme: 'metro',
    gridSize: { width: 22, height: 18 },
    playerSpawn: { x: 11, z: 16 },
    walls: [...createBoxRoom(22, 18), { x: 6, z: 9 }, { x: 16, z: 9 }],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_86', pos: { x: 2, z: 2 }, hp: 180, weapon: { ...rifle } },
      { id: 'me2_86', pos: { x: 20, z: 2 }, hp: 180, weapon: { ...rifle } },
    ],
    ammoBoxes: [{ id: 'ma86', pos: { x: 11, z: 9 } }],
    exit: { x: 11, z: 2 },
  },
  {
    id: 87,
    theme: 'metro',
    gridSize: { width: 28, height: 12 },
    playerSpawn: { x: 2, z: 2 },
    walls: [...createBoxRoom(28, 12), { x: 14, z: 1 }, { x: 14, z: 10 }],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_87', pos: { x: 26, z: 2 }, hp: 220, weapon: { ...rifle } },
      { id: 'me2_87', pos: { x: 26, z: 10 }, hp: 220, weapon: { ...rifle } },
    ],
    ammoBoxes: [{ id: 'ma7', pos: { x: 14, z: 6 } }],
    exit: { x: 26, z: 6 },
  },
  {
    id: 88,
    theme: 'metro',
    gridSize: { width: 20, height: 20 },
    playerSpawn: { x: 10, z: 18 },
    walls: [...createBoxRoom(20, 20), { x: 5, z: 10 }, { x: 15, z: 10 }],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_88', pos: { x: 2, z: 2 }, hp: 250, weapon: { ...rifle } },
      { id: 'me2_88', pos: { x: 18, z: 2 }, hp: 250, weapon: { ...rifle } },
    ],
    healthBoxes: [{ id: 'mh8', pos: { x: 2, z: 18 } }],
    exit: { x: 10, z: 2 },
  },
  {
    id: 89,
    theme: 'metro',
    gridSize: { width: 24, height: 16 },
    playerSpawn: { x: 2, z: 2 },
    walls: [...createBoxRoom(24, 16), { x: 8, z: 8 }, { x: 16, z: 8 }],
    hasTrain: true,
    timeLimit: 60,
    enemies: [
      { id: 'me1_89', pos: { x: 22, z: 2 }, hp: 300, weapon: { ...rifle } },
      { id: 'me2_89', pos: { x: 22, z: 14 }, hp: 300, weapon: { ...rifle } },
    ],
    ammoBoxes: [{ id: 'ma89', pos: { x: 12, z: 8 } }],
    exit: { x: 22, z: 8 },
  },
  {
    id: 90,
    theme: 'metro',
    gridSize: { width: 30, height: 20 },
    playerSpawn: { x: 15, z: 18 },
    walls: [...createBoxRoom(30, 20), { x: 10, z: 10 }, { x: 20, z: 10 }],
    hasTrain: true,
    timeLimit: 90,
    enemies: [
      { id: 'metromaster', pos: { x: 15, z: 2 }, hp: 1000, weapon: { ...rifle, damage: 40, ammo: 1000, maxAmmo: 1000 } },
      { id: 'me1_90', pos: { x: 5, z: 5 }, hp: 200, weapon: { ...shotgun } },
      { id: 'me2_90', pos: { x: 25, z: 5 }, hp: 200, weapon: { ...shotgun } },
    ],
    ammoBoxes: [{ id: 'ma10', pos: { x: 5, z: 15 } }, { id: 'ma10_2', pos: { x: 15, z: 10 } }],
    healthBoxes: [{ id: 'mh10', pos: { x: 25, z: 15 } }],
    exit: { x: 15, z: 1 },
  },
];
